version: '3.2'
services:
  core:
    build:
      context: ./
    container_name: test_task_container
    command: npm run start
    restart: on-failure
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_PASSWORD: postgres
      DB_USER: postgres
      DB_NAME: employeesdb
    ports:
      - 3000:3000
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: employeesdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app_network

networks:
  app_network:
volumes:
  pgdata:
